[project]
name = "collapsiblepane"
version = "0.1.0"
description = "A PySide6 widget for collapsible panels, inspired by JavaFX's TitledPane"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Muhammad Junaid Khalid", email = "mjk22071998@gmail.com"}
]
dependencies = ["PySide6>=6.0"]

[project.urls]
Homepage = "https://github.com/mjk22071998/CollapsiblePane"
Repository = "https://github.com/mjk22071998/CollapsiblePane"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
